/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.vista;

import com.sauces.controlador.Controlador;
import com.sauces.modelo.Cuenta;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFicheros = new javax.swing.JFileChooser();
        pCuenta = new javax.swing.JPanel();
        lCodigo = new javax.swing.JLabel();
        lTitular = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfTitular = new javax.swing.JTextField();
        tfSaldo = new javax.swing.JFormattedTextField();
        pListado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        tfBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuArchivos = new javax.swing.JMenu();
        miImportarArchivo = new javax.swing.JMenuItem();
        miExportarArchivo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSalir = new javax.swing.JMenuItem();
        menuBanco = new javax.swing.JMenu();
        miAbrirCuenta = new javax.swing.JMenuItem();
        miOperarCuenta = new javax.swing.JMenuItem();
        miCancelarCuenta = new javax.swing.JMenuItem();

        selectorFicheros.setCurrentDirectory(new java.io.File("."));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Sauces");

        pCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        lCodigo.setText("CÓDIGO");

        lTitular.setText("TITULAR");

        lSaldo.setText("SALDO");

        tfCodigo.setEditable(false);

        tfTitular.setEditable(false);

        tfSaldo.setEditable(false);
        tfSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCuentaLayout = new javax.swing.GroupLayout(pCuenta);
        pCuenta.setLayout(pCuentaLayout);
        pCuentaLayout.setHorizontalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuentaLayout.createSequentialGroup()
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCodigo)
                    .addComponent(lTitular)
                    .addComponent(lSaldo))
                .addGap(25, 25, 25)
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfTitular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addGap(0, 510, Short.MAX_VALUE))
        );
        pCuentaLayout.setVerticalGroup(
            pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitular)
                    .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lSaldo)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de cuentas"));

        cuentaTM=new CuentaTableModel();
        tablaCuentas.setModel(cuentaTM);
        tablaCuentas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=tablaCuentas.getSelectedRow();
                if(fila>=0){
                    mostrarCodigo((String)tablaCuentas.getValueAt(fila,0));
                    mostrarTitular((String)tablaCuentas.getValueAt(fila, 1));
                    mostrarSaldo((float)tablaCuentas.getValueAt(fila,2));
                }
            }
        });
        jScrollPane3.setViewportView(tablaCuentas);

        javax.swing.GroupLayout pListadoLayout = new javax.swing.GroupLayout(pListado);
        pListado.setLayout(pListadoLayout);
        pListadoLayout.setHorizontalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        pListadoLayout.setVerticalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        bBuscar.setText("BUSCAR");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        menuArchivos.setText("Archivo");
        menuArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivosActionPerformed(evt);
            }
        });

        miImportarArchivo.setText("Importar");
        miImportarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarArchivoActionPerformed(evt);
            }
        });
        menuArchivos.add(miImportarArchivo);

        miExportarArchivo.setText("Exportar");
        miExportarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExportarArchivoActionPerformed(evt);
            }
        });
        menuArchivos.add(miExportarArchivo);
        menuArchivos.add(jSeparator1);

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        menuArchivos.add(miSalir);

        menu.add(menuArchivos);

        menuBanco.setText("Banco");
        menuBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBancoActionPerformed(evt);
            }
        });

        miAbrirCuenta.setText("Abrir cuenta");
        miAbrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirCuentaActionPerformed(evt);
            }
        });
        menuBanco.add(miAbrirCuenta);

        miOperarCuenta.setText("Operar con cuenta");
        miOperarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOperarCuentaActionPerformed(evt);
            }
        });
        menuBanco.add(miOperarCuenta);

        miCancelarCuenta.setText("Cancelar cuenta");
        miCancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCancelarCuentaActionPerformed(evt);
            }
        });
        menuBanco.add(miCancelarCuenta);

        menu.add(menuBanco);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirCuentaActionPerformed
        limpiarCampos();
        if(dialogoCuenta.mostrar()==DialogoCuenta.ACEPTAR){
            mostrarCodigo(this.dialogoCuenta.getCodigo());
            mostrarTitular(this.dialogoCuenta.getTitular());
            mostrarSaldo(this.dialogoCuenta.getSaldo());
            controlador.abrirCuenta();
            dialogoCuenta.limpiarCampos();
        }
        else{
            mostrarMensaje("La cuenta no se ha podido abrir");
        }
    }//GEN-LAST:event_miAbrirCuentaActionPerformed

    private void menuBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBancoActionPerformed

    private void tfSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSaldoActionPerformed

    private void miOperarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOperarCuentaActionPerformed
        // TODO add your handling code here:
        controlador.operarConCuenta();
        actualizarTabla();
    }//GEN-LAST:event_miOperarCuentaActionPerformed

    private void miCancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCancelarCuentaActionPerformed
        // TODO add your handling code here:
        controlador.cancelarCuenta();
        actualizarTabla();
    }//GEN-LAST:event_miCancelarCuentaActionPerformed

    private void menuArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivosActionPerformed

    private void miExportarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExportarArchivoActionPerformed
       if(selectorFicheros.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
           controlador.exportarCuentas();
       }
    }//GEN-LAST:event_miExportarArchivoActionPerformed

    private void miImportarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarArchivoActionPerformed
        // TODO add your handling code here:
        if(selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
           controlador.importarCuentas();
       }
    }//GEN-LAST:event_miImportarArchivoActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        mostrarCodigo(tfBuscar.getText());
        controlador.buscarCuenta();
    }//GEN-LAST:event_bBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
       
        public void mostrar(){
            setVisible(true);
        }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public String getCodigo() {
        return tfCodigo.getText();
    }
    public String getTitular() {
        return tfTitular.getText();
    }
    public float getSaldo() {
        return Float.parseFloat(this.tfSaldo.getText().replace(',','.'));
    }
    public void mostrarCodigo(String codigo){
        this.tfCodigo.setText(codigo);
    }
    public void mostrarTitular(String titular){
        this.tfTitular.setText(titular);
    }
    public void mostrarSaldo(float saldo){
        this.tfSaldo.setValue(saldo);
    }
    public String getOperacion() {
        String operacion=(String)JOptionPane.showInputDialog(this, "Operación a realizar", "Operar con cuenta",JOptionPane.QUESTION_MESSAGE,null, new String[]{"INGRESAR","REINTEGRAR"},"INGRESAR");
        return operacion;
    }
    public float getCantidad(){
        return Float.parseFloat(JOptionPane.showInputDialog(this, "Introduzca cantidad"));
    }
    public String getArchivo(){
        return selectorFicheros.getSelectedFile().getAbsolutePath();
    }
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    public void mostrarCuentas(List<Cuenta> listado){
        cuentaTM.setCuentas(listado);
    }
    public void actualizarTabla(){
        tablaCuentas.revalidate();
    }
    public void limpiarCampos(){
        this.tfCodigo.setText("");
        this.tfTitular.setText("");
        this.tfSaldo.setValue(0.0);
    }
     private Controlador controlador;
        private CuentaTableModel cuentaTM;
        private DialogoCuenta dialogoCuenta=new DialogoCuenta(this,true);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lCodigo;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lTitular;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArchivos;
    private javax.swing.JMenu menuBanco;
    private javax.swing.JMenuItem miAbrirCuenta;
    private javax.swing.JMenuItem miCancelarCuenta;
    private javax.swing.JMenuItem miExportarArchivo;
    private javax.swing.JMenuItem miImportarArchivo;
    private javax.swing.JMenuItem miOperarCuenta;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JPanel pCuenta;
    private javax.swing.JPanel pListado;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JTable tablaCuentas;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JFormattedTextField tfSaldo;
    private javax.swing.JTextField tfTitular;
    // End of variables declaration//GEN-END:variables
}
